<a href="https://colab.research.google.com/github/silverstar0727/1day-1commit-challenge/blob/master/%EC%9E%AC%EB%AC%B4%EC%9E%AC%ED%91%9C_%ED%81%AC%EB%A1%A4%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import re
import requests

url_tmpl = 'http://companyinfo.stock.naver.com/v1/company/c1010001.aspx?cmp_cd=%s'
url = url_tmpl % ('005930' )

html_text = requests.get(url).text

encparam = re.findall ("encparam: '(.*?)'", html_text)[0]
encid = re.findall ("id: '(.*?)'", html_text)[0]

encparam, encid

('VzQ1ZjVWV1FybXh3cHdFblREZXhOUT09', 'ZTRzQlVCd0')

In [0]:
import pandas as pd
from io import StringIO

#  재무데이터 표 추출
url_tmpl = 'http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?' \
                'cmp_cd=%s&fin_typ=%s&freq_typ=%s&encparam=%s&id=%s'

url = url_tmpl % ('005930', '4', 'Y', encparam, encid) # 삼성전자, 4(IFRS 연결), Y:년 단위

header = {
    'Referer': 'https://companyinfo.stock.naver.com/v1/company/c1010001.aspx',
}

html_text = requests.get(url, headers=header).text
dfs = pd.read_html(StringIO(html_text))
df = dfs[1]

print(url)
df

http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?cmp_cd=005930&fin_typ=4&freq_typ=Y&encparam=VzQ1ZjVWV1FybXh3cHdFblREZXhOUT09&id=ZTRzQlVCd0

        주요재무정보                연간  ...
        주요재무정보 2014/12  (IFRS연결)  ... 2020/12(E)  (IFRS연결) 2021/12(E)  (IFRS연결)
0          매출액      2.062060e+06  ...           2523168.00           2769359.00
1         영업이익      2.502510e+05  ...            398805.00            530289.00
2   영업이익(발표기준)      2.502510e+05  ...                  NaN                  NaN
3     세전계속사업이익      2.787500e+05  ...            427108.00            564890.00
4        당기순이익      2.339440e+05  ...            310038.00            411026.00
5    당기순이익(지배)      2.308250e+05  ...            306716.00            407649.00
6   당기순이익(비지배)      3.119000e+03  ...                  NaN                  NaN
7         자산총계      2.304230e+06  ...           3783945.00           4135572.00
8         부채총계      6.233480e+05  ...            953425.00            995593.00
9         자본총계      1.680882e+06  ...           2830520.00           3139979.00
10    자본총계(지배)      1.621817e+06  ...           2747240.00           3056266.00
11   자본총계(비지배)      5.906500e+04  ...                  NaN                  NaN
12         자본금      8.975000e+03  ...              8979.00              8979.00
13    영업활동현금흐름      3.697540e+05  ...            564551.00            678797.00
14    투자활동현금흐름     -3.280640e+05  ...           -379937.00           -413606.00
15    재무활동현금흐름     -3.057100e+04  ...            -91576.00           -111436.00
16       CAPEX      2.204290e+05  ...            310611.00            335954.00
17         FCF      1.493240e+05  ...            250282.00            331570.00
18      이자발생부채      1.126550e+05  ...                  NaN                  NaN
19       영업이익률      1.214000e+01  ...                15.81                19.15
20        순이익률      1.134000e+01  ...                12.29                14.84
21      ROE(%)      1.506000e+01  ...                11.59                14.05
22      ROA(%)      1.053000e+01  ...                 8.46                10.38
23        부채비율      3.709000e+01  ...                33.68                31.71
24       자본유보율      1.937947e+04  ...                  NaN                  NaN
25      EPS(원)      2.713000e+03  ...              4515.00              6001.00
26      PER(배)      9.780000e+00  ...                13.33                10.03
27      BPS(원)      2.166400e+04  ...             40444.00             44994.00
28      PBR(배)      1.230000e+00  ...                 1.49                 1.34
29    현금DPS(원)      4.000000e+02  ...              1519.00              1565.00
30     현금배당수익률      1.510000e+00  ...                 2.52                 2.60
31   현금배당성향(%)      1.300000e+01  ...                29.57                22.91
32  발행주식수(보통주)      7.364967e+09  ...                  NaN                  NaN

[33 rows x 9 columns]

In [0]:
# 리스트로 전환
cols = list(df.columns)
cols

[('주요재무정보', '주요재무정보'),
 ('연간', '2014/12  (IFRS연결)'),
 ('연간', '2015/12  (IFRS연결)'),
 ('연간', '2016/12  (IFRS연결)'),
 ('연간', '2017/12  (IFRS연결)'),
 ('연간', '2018/12  (IFRS연결)'),
 ('연간', '2019/12(E)  (IFRS연결)'),
 ('연간', '2020/12(E)  (IFRS연결)'),
 ('연간', '2021/12(E)  (IFRS연결)')]

In [0]:
df.columns = [c[1] for c in cols]
df.columns

Index(['주요재무정보', '2014/12  (IFRS연결)', '2015/12  (IFRS연결)', '2016/12  (IFRS연결)',
       '2017/12  (IFRS연결)', '2018/12  (IFRS연결)', '2019/12(E)  (IFRS연결)',
       '2020/12(E)  (IFRS연결)', '2021/12(E)  (IFRS연결)'],
      dtype='object')

In [0]:
df = df.set_index('주요재무정보')
df.head(10) # 10개 항목만 표시(실제 32개 항목)

            2014/12  (IFRS연결)  ...  2021/12(E)  (IFRS연결)
주요재무정보                         ...
매출액                 2062060.0  ...             2769359.0
영업이익                 250251.0  ...              530289.0
영업이익(발표기준)           250251.0  ...                   NaN
세전계속사업이익             278750.0  ...              564890.0
당기순이익                233944.0  ...              411026.0
당기순이익(지배)            230825.0  ...              407649.0
당기순이익(비지배)             3119.0  ...                   NaN
자산총계                2304230.0  ...             4135572.0
부채총계                 623348.0  ...              995593.0
자본총계                1680882.0  ...             3139979.0

[10 rows x 8 columns]

In [0]:
import re
from datetime import datetime

s =  '\n\t\t\t\t\t\t\t\t\t2011/12\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t'

date_str = ''
r = re.search("\d{4}/\d{2}", s)
if r:
    date_str = r.group()

date_str

'2011/12'

In [0]:
import re
from datetime import datetime

def get_date_str(s):
    date_str = ''
    r = re.search("\d{4}/\d{2}", s)
    if r:
        date_str = r.group()
        date_str = date_str.replace('/', '-')

    return date_str

In [0]:
df.columns = [get_date_str(x) for x in df.columns]
df.columns

Index(['2014-12', '2015-12', '2016-12', '2017-12', '2018-12', '2019-12',
       '2020-12', '2021-12'],
      dtype='object')

In [0]:
import re
from datetime import datetime
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO

'''
get_date_str(s) - 문자열 s 에서 "YYYY/MM" 문자열 추출
'''
def get_date_str(s):
    date_str = ''
    r = re.search("\d{4}/\d{2}", s)
    if r:
        date_str = r.group()
        date_str = date_str.replace('/', '-')

    return date_str

'''
* code: 종목코드
* fin_type(종류): 0=주재무제표(기본), 1=GAAP개별, 2=GAAP연결, 3=IFRS별도, 4=FRS연결
* freq_type(기간): Y=년(기본), Q=분기
'''
def get_finstate_naver(code, fin_type='0', freq_type='Y'):
    # encparam, encid  추출
    url_tmpl = 'http://companyinfo.stock.naver.com/v1/company/c1010001.aspx?cmp_cd=%s'
    url = url_tmpl % ( code)

    html_text = requests.get(url).text
    if '기업재무정보 접속장애' in html_text:
      return None

    encparam = re.findall ("encparam: '(.*?)'", html_text)[0]
    encid = re.findall ("id: '(.*?)'", html_text)[0]

    #  재무데이터 표 추출
    url_tmpl = 'http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?' \
                    'cmp_cd=%s&fin_typ=%s&freq_typ=%s&encparam=%s&id=%s'

    url = url_tmpl % (code, fin_type, freq_type, encparam, encid)

    header = {
        'Referer': 'https://companyinfo.stock.naver.com/v1/company/c1010001.aspx',
    }

    html_text = requests.get(url, headers=header).text
    dfs = pd.read_html(StringIO(html_text))
    df = dfs[1]
    if df.iloc[0,0].find('해당 데이터가 존재하지 않습니다') >= 0:
        return None
    
    cols = list(df.columns)
    df.columns = [c[1] for c in cols]
    df.set_index('주요재무정보', inplace=True)
    df.columns = [get_date_str(x) for x in df.columns]
    
    return df

In [0]:
# 삼성전자 (년간, IFRS연결)
df = get_finstate_naver('005930', fin_type='3', freq_type='Q')
df

                 2018-09       2018-12       2019-03  ...  2019-12  2020-03  2020-06
주요재무정보                                                ...
매출액         4.764530e+05  3.881480e+05  3.703840e+05  ...      NaN      NaN      NaN
영업이익        1.391270e+05  7.536200e+04  3.896900e+04  ...      NaN      NaN      NaN
영업이익(발표기준)  1.391270e+05  7.536200e+04  3.896900e+04  ...      NaN      NaN      NaN
세전계속사업이익    1.388720e+05  7.848100e+04  4.154400e+04  ...      NaN      NaN      NaN
당기순이익       1.021150e+05  6.073100e+04  3.088600e+04  ...      NaN      NaN      NaN
당기순이익(지배)   1.021150e+05  6.073100e+04  3.088600e+04  ...      NaN      NaN      NaN
당기순이익(비지배)           NaN           NaN           NaN  ...      NaN      NaN      NaN
자산총계        2.177994e+06  2.190214e+06  2.206470e+06  ...      NaN      NaN      NaN
부채총계        4.814060e+05  4.603320e+05  4.689740e+05  ...      NaN      NaN      NaN
자본총계        1.696588e+06  1.729881e+06  1.737495e+06  ...      NaN      NaN      NaN
자본총계(지배)    1.696588e+06  1.729881e+06  1.737495e+06  ...      NaN      NaN      NaN
자본총계(비지배)            NaN           NaN           NaN  ...      NaN      NaN      NaN
자본금         8.975000e+03  8.975000e+03  8.975000e+03  ...      NaN      NaN      NaN
영업활동현금흐름    1.126900e+05  1.499830e+05  3.107000e+04  ...      NaN      NaN      NaN
투자활동현금흐름   -1.337950e+05 -9.428100e+04  2.866800e+04  ...      NaN      NaN      NaN
재무활동현금흐름    2.048600e+04 -6.882300e+04 -3.008800e+04  ...      NaN      NaN      NaN
CAPEX       3.948500e+04  3.694500e+04  2.821600e+04  ...      NaN      NaN      NaN
FCF         7.320500e+04  1.130380e+05  2.854000e+03  ...      NaN      NaN      NaN
이자발생부채      1.488140e+05  1.040280e+05  7.725400e+04  ...      NaN      NaN      NaN
영업이익률       2.920000e+01  1.942000e+01  1.052000e+01  ...      NaN      NaN      NaN
순이익률        2.143000e+01  1.565000e+01  8.340000e+00  ...      NaN      NaN      NaN
ROE(%)      2.341000e+01  2.022000e+01  1.664000e+01  ...      NaN      NaN      NaN
ROA(%)      1.807000e+01  1.573000e+01  1.289000e+01  ...      NaN      NaN      NaN
부채비율        2.838000e+01  2.661000e+01  2.699000e+01  ...      NaN      NaN      NaN
자본유보율       1.918315e+04  1.904811e+04  1.912423e+04  ...      NaN      NaN      NaN
EPS(원)      1.394000e+03  8.480000e+02  4.550000e+02  ...      NaN      NaN      NaN
PER(배)      9.280000e+00  8.590000e+00  1.163000e+01  ...      NaN      NaN      NaN
BPS(원)      2.497700e+04  2.546700e+04  2.557900e+04  ...      NaN      NaN      NaN
PBR(배)      1.860000e+00  1.520000e+00  1.750000e+00  ...      NaN      NaN      NaN
현금DPS(원)    3.540000e+02  3.540000e+02  3.540000e+02  ...      NaN      NaN      NaN
현금배당수익률     7.600000e-01           NaN           NaN  ...      NaN      NaN      NaN
현금배당성향(%)   2.355000e+01  3.961000e+01  7.785000e+01  ...      NaN      NaN      NaN
발행주식수(보통주)  6.419325e+09  5.969783e+09  5.969783e+09  ...      NaN      NaN      NaN

[33 rows x 8 columns]

In [0]:
df = get_finstate_naver('035720', fin_type='3', freq_type='Y')
df

                2014-12      2015-12      2016-12  ...  2019-12  2020-12  2021-12
주요재무정보                                             ...
매출액             4878.00      8621.00      8612.00  ...      NaN      NaN      NaN
영업이익            1825.00      1206.00       710.00  ...      NaN      NaN      NaN
영업이익(발표기준)      1825.00      1206.00       710.00  ...      NaN      NaN      NaN
세전계속사업이익        1792.00      1012.00       526.00  ...      NaN      NaN      NaN
당기순이익           1603.00       729.00       382.00  ...      NaN      NaN      NaN
당기순이익(지배)       1603.00       729.00       382.00  ...      NaN      NaN      NaN
당기순이익(비지배)          NaN          NaN          NaN  ...      NaN      NaN      NaN
자산총계           27558.00     31171.00     48293.00  ...      NaN      NaN      NaN
부채총계            2950.00      5422.00     14541.00  ...      NaN      NaN      NaN
자본총계           24608.00     25749.00     33752.00  ...      NaN      NaN      NaN
자본총계(지배)       24608.00     25749.00     33752.00  ...      NaN      NaN      NaN
자본총계(비지배)           NaN          NaN          NaN  ...      NaN      NaN      NaN
자본금              291.00       301.00       339.00  ...      NaN      NaN      NaN
영업활동현금흐름        2266.00      1886.00      2219.00  ...      NaN      NaN      NaN
투자활동현금흐름        1098.00     -5938.00     -9264.00  ...      NaN      NaN      NaN
재무활동현금흐름         354.00      2024.00      7908.00  ...      NaN      NaN      NaN
CAPEX            125.00       711.00       426.00  ...      NaN      NaN      NaN
FCF             2141.00      1175.00      1793.00  ...      NaN      NaN      NaN
이자발생부채             2.00      1996.00      9706.00  ...      NaN      NaN      NaN
영업이익률             37.42        13.99         8.24  ...      NaN      NaN      NaN
순이익률              32.86         8.46         4.43  ...      NaN      NaN      NaN
ROE(%)            12.15         2.90         1.28  ...      NaN      NaN      NaN
ROA(%)            10.78         2.48         0.96  ...      NaN      NaN      NaN
부채비율              11.99        21.06        43.08  ...      NaN      NaN      NaN
자본유보율           8441.28      8484.18      9886.88  ...      NaN      NaN      NaN
EPS(원)          6531.00      1223.00       578.00  ...      NaN      NaN      NaN
PER(배)            18.93        94.71       133.18  ...      NaN      NaN      NaN
BPS(원)         42443.00     42850.00     49921.00  ...      NaN      NaN      NaN
PBR(배)             2.91         2.70         1.54  ...      NaN      NaN      NaN
현금DPS(원)         173.00       167.00       148.00  ...   144.00   151.00   161.00
현금배당수익률            0.14         0.14         0.19  ...     0.09     0.08     0.08
현금배당성향(%)          6.26        13.77        26.21  ...      NaN      NaN      NaN
발행주식수(보통주)  58142204.00  60096088.00  67615715.00  ...      NaN      NaN      NaN

[33 rows x 8 columns]

In [0]:
#df = get_finstate_naver('035720') # 셀트리온 068270 
df = get_finstate_naver('035720') # 카카오 035720
#df = get_finstate_naver('035720') # CJ E&M 130960
#df = get_finstate_naver('035720') # 메디톡스 086900

df

                2014-12      2015-12      2016-12  ...   2019-12   2020-12   2021-12
주요재무정보                                             ...
매출액             4989.00      9322.00     14642.00  ...  30808.00  38273.00  44360.00
영업이익            1764.00       886.00      1161.00  ...   1962.00   4326.00   5710.00
영업이익(발표기준)      1764.00       886.00      1161.00  ...       NaN       NaN       NaN
세전계속사업이익        1688.00      1095.00      1003.00  ...   2675.00   4850.00   6338.00
당기순이익           1498.00       788.00       655.00  ...   1550.00   3252.00   4591.00
당기순이익(지배)       1501.00       757.00       577.00  ...   1764.00   3410.00   4713.00
당기순이익(비지배)        -3.00        31.00        78.00  ...       NaN       NaN       NaN
자산총계           27680.00     31885.00     54841.00  ...  85908.00  91135.00  98816.00
부채총계            3048.00      6030.00     17812.00  ...  27476.00  32582.00  35786.00
자본총계           24632.00     25855.00     37029.00  ...  58432.00  58554.00  63029.00
자본총계(지배)       24546.00     25524.00     34325.00  ...  53498.00  53574.00  58019.00
자본총계(비지배)         86.00       331.00      2704.00  ...       NaN       NaN       NaN
자본금              291.00       301.00       339.00  ...    423.00    424.00    424.00
영업활동현금흐름        2203.00      1622.00      3173.00  ...   6793.00   8260.00   8665.00
투자활동현금흐름        1726.00     -4142.00    -10000.00  ...  -2733.00  -4518.00  -4550.00
재무활동현금흐름         354.00      1972.00      9238.00  ...    -33.00    418.00    539.00
CAPEX            128.00       761.00       810.00  ...    988.00   1058.00   1172.00
FCF             2075.00       861.00      2363.00  ...   4233.00   6030.00   6349.00
이자발생부채             3.00      2218.00      9999.00  ...       NaN       NaN       NaN
영업이익률             35.37         9.50         7.93  ...      6.37     11.30     12.87
순이익률              30.03         8.45         4.47  ...      5.03      8.50     10.35
ROE(%)            11.41         3.02         1.93  ...      3.36      6.36      8.45
ROA(%)            10.04         2.65         1.51  ...      1.87      3.66      4.83
부채비율              12.37        23.32        48.10  ...     47.02     55.64     56.78
자본유보율           8411.95      8407.52     10068.46  ...       NaN       NaN       NaN
EPS(원)          6116.00      1269.00       874.00  ...   2101.00   3944.00   5452.00
PER(배)            20.21        91.24        88.15  ...     79.71     48.17     34.85
BPS(원)         42337.00     42476.00     50769.00  ...  65251.00  65161.00  70567.00
PBR(배)             2.92         2.73         1.52  ...      2.57      2.92      2.69
현금DPS(원)         173.00       167.00       148.00  ...    144.00    151.00    161.00
현금배당수익률            0.14         0.14         0.19  ...      0.09      0.08      0.08
현금배당성향(%)          6.68        13.26        17.35  ...      7.05      3.84      2.96
발행주식수(보통주)  58142204.00  60096088.00  67615715.00  ...       NaN       NaN       NaN

[33 rows x 8 columns]

In [0]:
dft = df.T

# 첫번째 컬럼 이름을 data로 변경
dft.rename(columns={'주요재무정보':'date'}, inplace=True)

# 인덱스를 날짜형식(datetime)으로 변환
dft.index = pd.to_datetime(dft.index)

# 필요한 컬럼만 출력해 본다
dft[['매출액', '당기순이익', '부채총계', 'PER(배)' , 'PBR(배)', '현금배당수익률']]

주요재무정보          매출액   당기순이익     부채총계  PER(배)  PBR(배)  현금배당수익률
2014-12-01   4989.0  1498.0   3048.0   20.21    2.92     0.14
2015-12-01   9322.0   788.0   6030.0   91.24    2.73     0.14
2016-12-01  14642.0   655.0  17812.0   88.15    1.52     0.19
2017-12-01  19723.0  1251.0  18865.0   85.50    2.31     0.11
2018-12-01  24170.0   159.0  23324.0  168.01    1.59     0.12
2019-12-01  30808.0  1550.0  27476.0   79.71    2.57     0.09
2020-12-01  38273.0  3252.0  32582.0   48.17    2.92     0.08
2021-12-01  44360.0  4591.0  35786.0   34.85    2.69     0.08